// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa2BCvXTEnqlyS-zUs7AkHMTh3OG-OM3k',
    appId: '1:126488977829:web:efd7bbfe428a07be4f084c',
    messagingSenderId: '126488977829',
    projectId: 'doctor-80e1f',
    authDomain: 'doctor-80e1f.firebaseapp.com',
    storageBucket: 'doctor-80e1f.appspot.com',
    measurementId: 'G-DBX8XPYMVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyXx1T0t17fZcrtirIoh-rBNZwYnMNOQA',
    appId: '1:126488977829:android:9b2b5a1a22dcb7864f084c',
    messagingSenderId: '126488977829',
    projectId: 'doctor-80e1f',
    storageBucket: 'doctor-80e1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN7XIHjMbr0F-Jk0rprvIpg-dxv0yIZcQ',
    appId: '1:126488977829:ios:c781743c2b43b4864f084c',
    messagingSenderId: '126488977829',
    projectId: 'doctor-80e1f',
    storageBucket: 'doctor-80e1f.appspot.com',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN7XIHjMbr0F-Jk0rprvIpg-dxv0yIZcQ',
    appId: '1:126488977829:ios:c3cae8895ba9eb904f084c',
    messagingSenderId: '126488977829',
    projectId: 'doctor-80e1f',
    storageBucket: 'doctor-80e1f.appspot.com',
    iosBundleId: 'com.example.doctor.RunnerTests',
  );
}
